### ISSUE TITLE
CSV file only has timestamp

### ISSUE THREAD

**Issue by chrisjbillington** [KalebKE/AccelerationExplorer#11]
After running the logger and finding the CSV file in phone storage, the CSV file doesn't contain any data other than the timestamps:

```
Timestamp,X,Y,Z
0.002
0.023
0.043
0.063
0.084
0.104
0.125
0.145
0.165
0.186
0.207
0.227
0.248
0.268
0.289
0.309
0.329
```

**Comment by Digolodollarz** [comment]
@chrisjbillington did you ever manage to fix this

**Comment by chrisjbillington** [comment]
I did not.

**Comment by Digolodollarz** [comment]
Okay, thanks. Any suggestions? I just need the values so that I can
calculate the frequency of the vibrations

**Comment by KalebKE** [comment]
Fixed in https://github.com/KalebKE/AccelerationExplorer/releases/tag/v3.3.1
